### ISSUE TITLE
Raw packets: ipxwrapper does not support 'Length' field in IEEE 802.3 frames

### ISSUE THREAD

**Issue by RAndrewThomas** [solemnwarning/ipxwrapper#1]
The Ethernet II standard describes the 2 octet field following the source MAC field as 'EtherType' while IEEE 802.3 describes it as 'Length'.  IEEE 802.3 resolves this apparent conflict: values in that 2 octet filed must be 1536 (decimal) or greater for the field to be considered 'EtherType'.  Values below 1536 are to be treated as 'Length'.

ipxwrapper assumes that field to be 'EtherType' always, and further requires that the field be equal to 0x8137 (IPX) in order to forward "raw" ipx packets to/from an application.  This prevents Windows applications from being able to use ipxwrapper to communicate with systems (in my case, embedded industrial controls) that generate IEEE 802.3 frames instead of Ethernet II frames.

I fixed the problem for myself by forcing the assumption in the other direction, requiring IEEE 802.3 frames only.  The affected source files are 'ipxwrapper.h',  'router.c' and 'winsock.c'.  However the correct fix would be to support both frame types, which might require additional type definitions for 'ethernet_frame' in 'ipxwrapper.h' and conditional handling wherever that type is used.

**Comment by RAndrewThomas** [comment]
I've forked ipxwrapper and will apply my current, equally standards-incompatible changes there.  I will try to come up with an overall compatible fix, but I do not have the resources to test old games, etc, to ensure that I don't break the base IPX wrapping feature.

**Comment by solemnwarning** [comment]
I'll add an option to allow choosing between "raw" frames and Ethernet II. I considered doing this originally, but wasn't sure which types were in use in the wild (The Microsoft protocol driver supported 4 types).

**Comment by solemnwarning** [comment]
Current master seems to be working with simulated Novell frames. Can you try it and let me know if it works for you? You will need to change the frame type using ipxconfig.

Thanks

**Comment by RAndrewThomas** [comment]
Getting close, but not quite there.  My packets are still being dropped in router.c, but after some digging, I know how to describe what's missing:

In 802.3 frames, the 802.2 LLC header immediately follows the 802.3 header.  This amounts to 3 additional bytes before the actual payload.  The first two bytes should be 0xe0, specifying 'Novell Netware' for the DSAP and SSAP fields.  The third byte (Control Field) should be 0x03 to support connectionless IPX packets.  That last field may preclude SPX communications but ipxwrapper doesn't support that anyway.

Here are the kludges I made to 0.60 ipxwrapper to make it work for me: https://pastebin.com/BQ4xkLzA

Here is a very small (4 packets) capture of one of my machines attempting to make an IPX connection:
https://drive.google.com/open?id=0BwJmJQV9_KRcSFlfcHdudXEyTGc

**Comment by solemnwarning** [comment]
Right, LLC encapsulation.

I've done a load of reworking of the Ethernet frame handling code and added LLC support in the llc-support branch, could you give that a try? You'll need to run ipxconfig again and select LLC framing.

Thanks

**Comment by RAndrewThomas** [comment]
That did it!

Now the home-grown IPX file transfer protocol we came up with in the early '90s works and the contents of the transferred files is good.  And with a legitimate implementation, unlike my kludge.

Thank you for the effort.

**Comment by solemnwarning** [comment]
Released in IPXWrapper 0.6.1
