### ISSUE TITLE
Disable all logging / Clear log on startup

### ISSUE THREAD

**Issue by Carlmundo** [solemnwarning/ipxwrapper#18]
Hello,

Is it possible to add an option to disable all logging to ipxwrapper.log and/or clear the log file contents upon initialisation?

**Comment by solemnwarning** [comment]
Not against such a feature, although it's not quite straightforward due to the log being opened by multiple DLLs and potentially multiple processes - could work off a semaphore or something to detect "first" open perhaps.

**Comment by Carlmundo** [comment]
Thanks for the reponse. In that case, is it possible to set the log level to none, so that nothing is written to the log file?

**Comment by solemnwarning** [comment]
There's no option in the UI for it right now, but setting the `log_level` value to 7 in `HKEY_CURRENT_USER\Software\IPXWrapper` should suppress all logging.

**Comment by Carlmundo** [comment]
> There's no option in the UI for it right now, but setting the `log_level` value to 7 in `HKEY_CURRENT_USER\Software\IPXWrapper` should suppress all logging.

Great, thank you!

**Comment by Carlmundo** [comment]
I have tested this and while it is not a big deal, it still adds 2 lines, and keeps appending to the log file each time it is called.

[14587.78, thread 4904] IPXWrapper 0.7.0
[14587.78, thread 4904] Compiled at Thu 19 Oct 09:29:09 BST 2023
