### ISSUE TITLE
"Send and receive real IPX packts" GUI option is poorly placed and confusing

### ISSUE THREAD

**Issue by JayFoxRox** [solemnwarning/ipxwrapper#4]
"Send and receive real IPX packets" which is the option at the very bottom will hide actual IP interfaces in the adapter selection at the very top.

This is confusing to users because they can't find the device they are looking for with no hint what might be going on.

In our case, someone wanted to use Hamachi but could not find the correct adapter / device.
We only traced it back to this option when their log file did not contain any IP device, but instead contained pcap. - if I wasn't familar with network programming and pcap, I probably wouldn't even have been able to figure this out.

The option should be renamed (something like: "Don't use IP device (Send and receive real IPX packets)") and moved to the very top instead.

**Comment by solemnwarning** [comment]
![image](https://github.com/solemnwarning/ipxwrapper/assets/9392044/2ddf5ca8-941d-44b6-8659-f5158bb7404f)
