### ISSUE TITLE
moto racer

### ISSUE THREAD

**Issue by legluondunet** [solemnwarning/ipxwrapper#7]
Hello,
do you know why your ipxwrapper does not work with Moto Racer 1 and 2?

**Comment by solemnwarning** [comment]
Hello,
I haven't encountered either of them. How does it not work? Do you have an ipxwrapper.log from either of them?

**Comment by legluondunet** [comment]
sorry it finally work, impressive, thanks!!!

**Comment by legluondunet** [comment]
it finally work...I was a little too positive. Could you tell me if ipxwrapper is compatible with Wine on Linux? I overrided swsock232.dll for the games (Moto Racer 1 and Star Wars racer) enable multiplayer mode via ipx. For my tests I launched two different installation of the same game on the same computer.

**Comment by solemnwarning** [comment]
It isn't officially supported, but I think it worked last time I tried it.

Can you go into more detail on how its failing? If you've redirected the DLLs in winecfg, that might cause problems, as the IPXWrapper wsock32.dll needs to be able to load the system one.

**Comment by legluondunet** [comment]
I overrided swsock32.dll to "native, builtin" or the game did not find ipx connection available:

![ipxwrapperwine](https://user-images.githubusercontent.com/325405/57190927-5b207080-6f20-11e9-8606-252b444bda06.jpg)

Perhaps two launched game on the same computer can not communicate together with ipxwrapper because they are using the same mac address/node?

**Comment by legluondunet** [comment]
I joined you a little extract of the log:
[ipxwrapper.log](https://github.com/solemnwarning/ipxwrapper/files/3145305/ipxwrapper.log)

**Comment by solemnwarning** [comment]
Oh, I missed that both instances were running on the same computer in your earlier message. That could be the problem.

**Comment by legluondunet** [comment]
@solemnwarning Is Motoracer 1 et 2 IPXWrapper compatible? I tried on WIndows it doesn't seem to work neither.

**Comment by solemnwarning** [comment]
Sorry for taking so long to reply, I'm away from home for a few weeks.

As far as I know, noone's ever tried it before. I can take a look probably next month if you can send me a copy of the game.

**Comment by legluondunet** [comment]
I can offer you this 2 games if you engage to add IPXWrapper compatibility for this games and on Wine too.

**Comment by solemnwarning** [comment]
If it turns out the games don't work under IPXWrapper, I will fix it, so long as it is feasible.

**Comment by legluondunet** [comment]
Do you have a Gog account? If so could you add me as friend?

**Comment by solemnwarning** [comment]
I don't, but sent an invite to you from someone else's account.

**Comment by legluondunet** [comment]
I have two new friends, which one are you, which one will receive the games gift?

**Comment by solemnwarning** [comment]
I haven't had a lot of time to put towards this project, but here's a quick update:

The game uses DirectPlay, specifically the `IDirectPlay2A` interface. The IPXWrapper Service Provider DLL gets loaded and the game enumerates sessions using it, but never actually creates a session, even when sat in the lobby screen as a host. Swapping in the Windows XP Service Provider DLL seems to have exactly the same effect, suggesting either a bug in the game, or in DirectPlay itself (`IDirectPlay2A` is from DirectX 3, so perhaps not very well maintained these days).

I'll investigate a bit further when I have a chance and see if there is anything IPXWrapper can do to work around the bug wherever it is.

**Comment by legluondunet** [comment]
Hello, do you have some news about this issue?

**Comment by solemnwarning** [comment]
I haven't made any progress on this I'm afraid

**Comment by legluondunet** [comment]
Motoracer 1 et 2 multiplayer mode finally works on Linux with Wine.
You have to install directplay with winetricks.

**Comment by Siljo1** [comment]
But it does not work on windows. help please
